GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/notes/64bb4c929b4844d9481a150c

####
DELETE  http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Ejemplo de nota",
    "important": true
}

