GET http://localhost:3001/api/blogs

####
GET http://localhost:3001/api/blogs/64bf543a138edbd8252e6406

####

DELETE  http://localhost:3001/api/blogs/1

####

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "Title":"Probando el blog",
    "author":"Gonzalo Masa",
    "url":"www.blog.com.ar",
    "likes": 5
}