GET http://localhost:3001/api/blogs

####

GET http://localhost:3001/api/blogs/64bf543a138edbd8252e6406

####

DELETE http://localhost:3001/api/blogs/64c7d48a7c4f15934ccb0003

####

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Probando el blog",
    "author":"Gonzalo Masa",
    "url":"www.blog.com.ar",
    "likes": 5,
    "userId":"64ce7d3d947cf0359efa7f6f"
}




